/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.2/samples
 */

description = "Gralde for Kurajj charity platform"
version = "0.0.1"

tasks.register("serverBuild") {
    group = "build"
    description = "Builds binary of project"
    val binaryDir: String by extra { properties.getOrDefault("dir", "bin") as String }
    val binaryName: String by extra { properties.getOrDefault("name", "kurajj_server") as String }
    doLast {
        exec {
            commandLine = listOf("go", "build", "-o", "./${binaryDir}/${binaryName}", "-a", ".")
        }
    }
}

tasks.register("serverDockerBuild") {
    group = "docker"
    description = "Builds server image by Dockerfile"
    val version: Int by extra { properties.getOrDefault("v", 1) as Int }
    val kvServerDockerName: String by extra { properties.getOrDefault("dockerName", "miprokop/kurajj_charity_planform") as String }
    doLast {
        exec {
            commandLine = listOf("docker", "build", "-t", "${kvServerDockerName}:v$version", "-f", "server/Dockerfile", ".")
        }
    }
}

tasks.register("serverDockerPush") {
    group = "docker"
    description = "Pushes the Kurajj Charity Planform docker image to Dockerhub"
    val version: Int by extra { properties.getOrDefault("v", 1) as Int }
    val kvServerDockerName: String by extra { properties.getOrDefault("dockerName", "miprokop/kurajj_charity_planform") as String }
    doLast {
        exec {
            commandLine = listOf("docker", "push",  "${kvServerDockerName}:v$version")
        }
    }
}
