apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "charity-platform.fullname" . }}
  namespace: {{ include "charity-platform.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
spec:
  rules:
    - host: united-ua.charity-platform.api
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "charity-platform.fullname" . }}
                port:
                  number: 8080
