{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "charity-platform.serviceAccountName" . }}
  namespace: {{ include "charity-platform.fullname" . }}
  labels:
    {{- include "charity-platform.labels" . | nindent 4 }}
{{- end }}
