// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "mykha"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Create a new admin",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.AdminCreation"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.CreationResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/events/proposal/accept": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Proposal Event"
                ],
                "summary": "Update proposal event transaction's status to models.InProcess state",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/events/proposal/comment": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Proposal Event"
                ],
                "summary": "Create new comment in proposal event",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.CommentCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.CreationResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/events/proposal/comment/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Proposal Event"
                ],
                "summary": "Update proposal event comment",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.CommentUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Proposal Event"
                ],
                "summary": "Update proposal event comment",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/events/proposal/comments/id": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Proposal Event"
                ],
                "summary": "Take all comments in proposal event by its id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.Comments"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/events/proposal/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Proposal Event"
                ],
                "summary": "Create a new proposal event",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ProposalEventRequestCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.CreationResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/events/proposal/delete/{id}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Proposal Event"
                ],
                "summary": "Delete proposal event",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/events/proposal/get": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Proposal Event"
                ],
                "summary": "Get all proposal events",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ProposalEvents"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/events/proposal/get-own": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Proposal Event"
                ],
                "summary": "Get all proposal events created by user requester id",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ProposalEvents"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/events/proposal/get/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Proposal Event"
                ],
                "summary": "Get proposal event by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ProposalEventGetResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/events/proposal/response": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Proposal Event"
                ],
                "summary": "Create new transaction with waiting status for the proposal event if slot is available",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/events/proposal/transactions/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Proposal Event"
                ],
                "summary": "Update proposal event comment",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.TransactionsExport"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/events/proposal/update-status/{id}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Proposal Event"
                ],
                "summary": "Update proposal event transaction's status to to one of models.Status state",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/events/proposal/update/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Proposal Event"
                ],
                "summary": "Update proposal event",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ProposalEventRequestUpdate"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    }
                }
            }
        },
        "/auth/confirm/{email}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Updates user's status to activated.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email",
                        "name": "email",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    }
                }
            }
        },
        "/auth/sign-in": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Signs In a user",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.SignInEntity"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.SignedInUser"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    }
                }
            }
        },
        "/auth/sign-in-admin": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Signs In a user",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.SignInEntity"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.SignedInUser"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    }
                }
            }
        },
        "/auth/sign-up": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Signs Up new user",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.SignUpUser"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.CreationResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Kurajj_internal_models.ErrResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Kurajj_internal_models.Address": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "homeLocation": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                }
            }
        },
        "Kurajj_internal_models.AdminCreation": {
            "type": "object",
            "properties": {
                "companyName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "secondName": {
                    "type": "string"
                },
                "telephone": {
                    "type": "string"
                }
            }
        },
        "Kurajj_internal_models.Comment": {
            "type": "object",
            "properties": {
                "creationDate": {
                    "type": "string"
                },
                "eventID": {
                    "type": "integer"
                },
                "eventType": {
                    "$ref": "#/definitions/Kurajj_internal_models.EventType"
                },
                "id": {
                    "type": "integer"
                },
                "isDeleted": {
                    "type": "boolean"
                },
                "isUpdated": {
                    "type": "boolean"
                },
                "text": {
                    "type": "string"
                },
                "updatedAt": {
                    "$ref": "#/definitions/sql.NullTime"
                },
                "userID": {
                    "type": "integer"
                }
            }
        },
        "Kurajj_internal_models.CommentCreateRequest": {
            "type": "object",
            "properties": {
                "eventId": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "Kurajj_internal_models.CommentResponse": {
            "type": "object",
            "properties": {
                "authorId": {
                    "type": "integer"
                },
                "creationDate": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isUpdated": {
                    "type": "boolean"
                },
                "profileImageURL": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "updateTime": {
                    "$ref": "#/definitions/sql.NullTime"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "Kurajj_internal_models.CommentUpdateRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "Kurajj_internal_models.Comments": {
            "type": "object",
            "properties": {
                "comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Kurajj_internal_models.CommentResponse"
                    }
                }
            }
        },
        "Kurajj_internal_models.CreationResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "Kurajj_internal_models.ErrResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "Kurajj_internal_models.EventType": {
            "type": "string",
            "enum": [
                "proposal-event"
            ],
            "x-enum-varnames": [
                "ProposalEventType"
            ]
        },
        "Kurajj_internal_models.ProposalEventGetResponse": {
            "type": "object",
            "properties": {
                "authorID": {
                    "type": "integer"
                },
                "availableHelps": {
                    "type": "integer"
                },
                "category": {
                    "type": "string"
                },
                "comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Kurajj_internal_models.Comment"
                    }
                },
                "competitionDate": {
                    "type": "string"
                },
                "creationDate": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "maxConcurrentRequests": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "transactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Kurajj_internal_models.TransactionResponse"
                    }
                }
            }
        },
        "Kurajj_internal_models.ProposalEventRequestCreate": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "maxConcurrentRequests": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "Kurajj_internal_models.ProposalEventRequestUpdate": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "competitionDate": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "Kurajj_internal_models.ProposalEvents": {
            "type": "object",
            "properties": {
                "proposalEvents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Kurajj_internal_models.ProposalEventGetResponse"
                    }
                }
            }
        },
        "Kurajj_internal_models.SignInEntity": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "Kurajj_internal_models.SignUpUser": {
            "type": "object",
            "properties": {
                "address": {
                    "$ref": "#/definitions/Kurajj_internal_models.Address"
                },
                "companyName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "secondName": {
                    "type": "string"
                },
                "telephone": {
                    "type": "string"
                }
            }
        },
        "Kurajj_internal_models.SignedInUser": {
            "type": "object",
            "properties": {
                "address": {
                    "$ref": "#/definitions/Kurajj_internal_models.Address"
                },
                "companyName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "secondName": {
                    "type": "string"
                },
                "telephone": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "Kurajj_internal_models.Status": {
            "type": "string",
            "enum": [
                "in_process",
                "completed",
                "interrupted",
                "canceled",
                "waiting"
            ],
            "x-enum-varnames": [
                "InProcess",
                "Completed",
                "Interrupted",
                "Canceled",
                "Waiting"
            ]
        },
        "Kurajj_internal_models.TransactionResponse": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "competitionDate": {
                    "type": "string"
                },
                "creatorID": {
                    "type": "integer"
                },
                "eventID": {
                    "type": "integer"
                },
                "eventType": {
                    "$ref": "#/definitions/Kurajj_internal_models.EventType"
                },
                "id": {
                    "type": "integer"
                },
                "responderStatus": {
                    "$ref": "#/definitions/Kurajj_internal_models.Status"
                },
                "transactionStatus": {
                    "$ref": "#/definitions/Kurajj_internal_models.Status"
                }
            }
        },
        "Kurajj_internal_models.TransactionsExport": {
            "type": "object",
            "properties": {
                "transactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Kurajj_internal_models.TransactionResponse"
                    }
                }
            }
        },
        "sql.NullTime": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Swagger Cor Charity Platform",
	Description:      "Kurajj Charity Platform",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
